[package]
name = "nut"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.53", features = ["derive"] }
directories = "6.0.0"
octocrab = "0.48.0"
ulid = "1.2.1"
